server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://192.168.10.10:3306/emall
    username: homestead
    password: secret
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka